licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h*"]),
    deps = [
#        "@com_github_grpc_grpc//:grpc++",
#        "@absl//absl/strings:strings",
    ],
    copts = ["-Wall", "-Werror"],
)
