licenses(["notice"])

package(default_visibility = ["//visibility:public"])


cc_test(
  name = "test_common",
  srcs = ["test_common.cc"],
  deps = [
    "//common:common",
    "@com_google_googletest//:gtest_main",
  ],
)
